# You have to put ssh host in github secret, then it will work
name: Build and deploy to Docker Hub and EC2

on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: zafar8588/omegle:${{ github.run_number }}

      - name: Verify Pushed Image
        run: docker pull zafar8588/omegle:${{ github.run_number }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            IMAGE_TAG=${{ github.run_number }}
            sudo docker pull zafar8588/omegle:$IMAGE_TAG
            sudo docker stop omegle || true
            sudo docker rm omegle || true
            sudo docker run -d --name omegle -p 3000:3000 \
              zafar8588/omegle:$IMAGE_TAG
            sudo docker ps | grep omegle
